-- Migration: Add PTZ Client Latency table
-- Date: January 1, 2026
-- Description: Stores learned ONVIF PTZ latency per client/camera pair
--              for optimizing stop timing based on observed response times

-- Ensure the update_updated_at_column function exists
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Check if table already exists
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_tables WHERE tablename = 'ptz_client_latency') THEN
        -- Create the table
        CREATE TABLE ptz_client_latency (
            -- Primary key
            id BIGSERIAL PRIMARY KEY,

            -- Client identification (UUID generated by browser, stored in localStorage)
            client_uuid VARCHAR(36) NOT NULL,

            -- Camera identification
            camera_serial VARCHAR(50) NOT NULL,

            -- Latency statistics
            avg_latency_ms INTEGER NOT NULL DEFAULT 1000,
            samples JSONB DEFAULT '[]'::jsonb,
            sample_count INTEGER DEFAULT 0,

            -- Timestamps
            created_at TIMESTAMPTZ DEFAULT NOW(),
            updated_at TIMESTAMPTZ DEFAULT NOW(),

            -- Unique constraint: one record per client/camera pair
            CONSTRAINT ptz_client_latency_unique
                UNIQUE (client_uuid, camera_serial)
        );

        -- Index for fast lookups
        CREATE INDEX idx_ptz_client_latency_lookup
            ON ptz_client_latency(client_uuid, camera_serial);

        -- Auto-update updated_at on row changes
        CREATE TRIGGER update_ptz_client_latency_updated_at
            BEFORE UPDATE ON ptz_client_latency
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();

        -- Grant permissions
        GRANT SELECT, INSERT, UPDATE ON ptz_client_latency TO nvr_anon;
        GRANT USAGE, SELECT ON SEQUENCE ptz_client_latency_id_seq TO nvr_anon;

        -- RLS policy
        ALTER TABLE ptz_client_latency ENABLE ROW LEVEL SECURITY;

        CREATE POLICY "Allow all for ptz_client_latency"
        ON ptz_client_latency
        FOR ALL
        TO nvr_anon
        USING (true)
        WITH CHECK (true);

        RAISE NOTICE 'Created ptz_client_latency table';
    ELSE
        RAISE NOTICE 'ptz_client_latency table already exists, skipping';
    END IF;
END $$;
