FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    libgstreamer1.0-0 \
    libgstreamer-plugins-base1.0-0 \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    gstreamer1.0-rtsp \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

CMD ["/usr/local/bin/neolink", "rtsp", "--config=/etc/neolink.toml"]