#!/bin/bash
#
# update_go2rtc_config.sh
# Syncs go2rtc.yaml video relay streams with NEOLINK cameras from cameras.json
#
# Called by start.sh before container startup.
#
# go2rtc.yaml has two sections:
#   1. STATIC (top): API settings, RTSP/WebRTC ports, audio backchannel streams (ONVIF, Eufy)
#      These are hand-maintained and NOT touched by this script.
#
#   2. AUTO-GENERATED (bottom): Video relay streams for Neolink cameras
#      Camera -> Neolink (Baichuan->RTSP) -> go2rtc (RTSP in, WebRTC out) -> Browser
#      This section is regenerated by this script from cameras.json.
#
# The boundary between sections is the marker line:
#   "# VIDEO RELAY STREAMS"
# Everything above (inclusive of marker header) is preserved.
# Everything below the marker block is regenerated.
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
CAMERAS_JSON="${PROJECT_DIR}/config/cameras.json"
GO2RTC_YAML="${PROJECT_DIR}/config/go2rtc.yaml"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}Updating go2rtc.yaml video relay streams...${NC}"

if [[ ! -f "$CAMERAS_JSON" ]]; then
    echo -e "${RED}Error: cameras.json not found at $CAMERAS_JSON${NC}"
    exit 1
fi

if [[ ! -f "$GO2RTC_YAML" ]]; then
    echo -e "${RED}Error: go2rtc.yaml not found at $GO2RTC_YAML${NC}"
    echo -e "${YELLOW}Hint: Copy config/go2rtc.yaml.example to config/go2rtc.yaml${NC}"
    exit 1
fi

# Extract NEOLINK cameras from cameras.json
# These are Reolink cameras that speak Baichuan only (no native RTSP)
# Neolink bridges Baichuan -> RTSP, and go2rtc relays RTSP -> WebRTC
NEOLINK_CAMERAS=$(jq -r '
    .devices | to_entries[] |
    select(.value.stream_type == "NEOLINK" or .value.stream_type == "GO2RTC" or .value.stream_type == "NEOLINK_LL_HLS") |
    select(.value.type == "reolink") |
    {
        serial: .key,
        name: .value.name,
        stream: (.value.neolink.stream // "mainStream")
    } | @json
' "$CAMERAS_JSON")

# Marker line that separates static from auto-generated section
MARKER="# VIDEO RELAY STREAMS"

# Preserve everything up to and including the marker header block
# Find the line number of the marker
MARKER_LINE=$(grep -n "$MARKER" "$GO2RTC_YAML" | head -1 | cut -d: -f1)

if [[ -z "$MARKER_LINE" ]]; then
    echo -e "${YELLOW}Warning: Marker '$MARKER' not found in go2rtc.yaml${NC}"
    echo -e "${YELLOW}Appending video relay section to end of file${NC}"
    # No marker found — append everything to the end
    STATIC_PART=$(cat "$GO2RTC_YAML")
else
    # Keep everything up to (but not including) the marker line
    # We subtract 1 because the marker line itself plus its surrounding comments
    # are part of the auto-generated section header
    # Find the "# ========" line right before the marker
    HEADER_START=$((MARKER_LINE - 1))
    # Walk backwards to find where the separator block starts
    while [[ $HEADER_START -gt 0 ]]; do
        LINE=$(sed -n "${HEADER_START}p" "$GO2RTC_YAML")
        if echo "$LINE" | grep -q "^  # ==="; then
            break
        fi
        HEADER_START=$((HEADER_START - 1))
    done

    if [[ $HEADER_START -gt 1 ]]; then
        STATIC_PART=$(head -n $((HEADER_START - 1)) "$GO2RTC_YAML")
    else
        STATIC_PART=$(cat "$GO2RTC_YAML")
    fi
fi

# Count cameras
if [[ -z "$NEOLINK_CAMERAS" ]]; then
    CAMERA_COUNT=0
else
    CAMERA_COUNT=$(echo "$NEOLINK_CAMERAS" | wc -l)
fi

echo -e "${CYAN}Found $CAMERA_COUNT Neolink camera(s) for go2rtc video relay${NC}"

# Write the static part
echo "$STATIC_PART" > "$GO2RTC_YAML"

# Ensure trailing newline
echo "" >> "$GO2RTC_YAML"

# Write the auto-generated video relay section header
cat >> "$GO2RTC_YAML" << 'EOF'
  # =========================================================================
  # VIDEO RELAY STREAMS (low-latency path via go2rtc WebRTC)
  # =========================================================================
  # AUTO-GENERATED by scripts/update_go2rtc_config.sh from cameras.json
  # DO NOT EDIT BELOW THIS LINE — changes will be overwritten on restart
  #
  # These read from Neolink's RTSP output and serve WebRTC directly to browser.
  # go2rtc regenerates proper timestamps from Neolink's broken DTS=0 stream.
  # Browser selects "GO2RTC" stream type in UI to use this path.
  #
  # Path: Camera (Baichuan:9000) -> Neolink (RTSP:8554) -> go2rtc -> WebRTC -> Browser
  #
  # NOTE: This does NOT conflict with the audio-only ONVIF streams above.
  # ONVIF streams use a separate protocol/connection for backchannel audio.
EOF

# Add each Neolink camera as a video relay stream
if [[ -n "$NEOLINK_CAMERAS" ]]; then
    echo "$NEOLINK_CAMERAS" | while read -r camera_json; do
        serial=$(echo "$camera_json" | jq -r '.serial')
        name=$(echo "$camera_json" | jq -r '.name')
        stream=$(echo "$camera_json" | jq -r '.stream')

        echo "" >> "$GO2RTC_YAML"
        cat >> "$GO2RTC_YAML" << EOF
  # $name ($serial)
  # Baichuan-only camera, Neolink bridges to RTSP
  $serial:
    - "rtsp://neolink:8554/$serial/$stream"
EOF

        echo -e " ${GREEN}+${NC} $name ($serial) — $stream"
    done
fi

echo -e "${GREEN}Done! go2rtc.yaml updated with $CAMERA_COUNT video relay stream(s)${NC}"
