#!/bin/bash
#
# update_go2rtc_config.sh
# Syncs go2rtc.yaml video relay streams with ALL cameras from cameras.json
#
# Called by start.sh before container startup.
#
# go2rtc.yaml has two sections:
#   1. STATIC (top): API settings, RTSP/WebRTC ports, ONVIF backchannel streams,
#      Eufy P2P entry for doorbell. Hand-maintained — NOT touched by this script.
#
#   2. AUTO-GENERATED (bottom): Video relay streams for all cameras that have
#      a go2rtc_source field in cameras.json.
#      Source URL format uses ${ENV_VAR} for credentials (go2rtc substitutes at runtime).
#
# The boundary between sections is the marker line:
#   "# VIDEO RELAY STREAMS"
# Everything above (inclusive of marker header) is preserved.
# Everything below the marker block is regenerated.
#
# Source URL examples by type:
#   Neolink/Baichuan:  rtsp://neolink:8554/{serial}/mainStream
#   Reolink RTSP:      rtsp://${NVR_REOLINK_API_USER}:${NVR_REOLINK_API_PASSWORD}@{host}/h264Preview_01_main
#   Eufy:              eufy://${NVR_EUFY_BRIDGE_USERNAME}:${NVR_EUFY_BRIDGE_PASSWORD}@{serial}
#   Amcrest:           rtsp://${NVR_AMCREST_LOBBY_USERNAME}:${NVR_AMCREST_LOBBY_PASSWORD}@{host}/cam/realmonitor?channel=1&subtype=0
#   SV3C:              rtsp://admin:${NVR_SV3C_PASSWORD}@{host}:554/stream1
#   UniFi:             null (token-based, not configured here)
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
CAMERAS_JSON="${PROJECT_DIR}/config/cameras.json"
GO2RTC_YAML="${PROJECT_DIR}/config/go2rtc.yaml"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}Updating go2rtc.yaml video relay streams...${NC}"

if [[ ! -f "$CAMERAS_JSON" ]]; then
    echo -e "${RED}Error: cameras.json not found at $CAMERAS_JSON${NC}"
    exit 1
fi

if [[ ! -f "$GO2RTC_YAML" ]]; then
    echo -e "${RED}Error: go2rtc.yaml not found at $GO2RTC_YAML${NC}"
    echo -e "${YELLOW}Hint: Copy config/go2rtc.yaml.example to config/go2rtc.yaml${NC}"
    exit 1
fi

# Extract all cameras that have a non-null go2rtc_source field.
# go2rtc_source is the URL template go2rtc uses to connect to the camera.
# The ${ENV_VAR} substitutions in the URL are resolved by go2rtc at runtime
# from environment variables injected by docker-compose.
CAMERAS=$(jq -r '
    .devices | to_entries[] |
    select(.value.go2rtc_source != null and .value.go2rtc_source != "") |
    {
        serial: .key,
        name: .value.name,
        source: .value.go2rtc_source
    } | @json
' "$CAMERAS_JSON")

# Marker line separating static from auto-generated section
MARKER="# VIDEO RELAY STREAMS"

# Find the line number of the marker
MARKER_LINE=$(grep -n "$MARKER" "$GO2RTC_YAML" | head -1 | cut -d: -f1)

if [[ -z "$MARKER_LINE" ]]; then
    echo -e "${YELLOW}Warning: Marker '$MARKER' not found in go2rtc.yaml${NC}"
    echo -e "${YELLOW}Appending video relay section to end of file${NC}"
    STATIC_PART=$(cat "$GO2RTC_YAML")
else
    # Walk backwards from marker to find the start of the separator block
    # (the "# ===" line immediately before the marker)
    HEADER_START=$((MARKER_LINE - 1))
    while [[ $HEADER_START -gt 0 ]]; do
        LINE=$(sed -n "${HEADER_START}p" "$GO2RTC_YAML")
        if echo "$LINE" | grep -q "^  # ==="; then
            break
        fi
        HEADER_START=$((HEADER_START - 1))
    done

    if [[ $HEADER_START -gt 1 ]]; then
        STATIC_PART=$(head -n $((HEADER_START - 1)) "$GO2RTC_YAML")
    else
        STATIC_PART=$(cat "$GO2RTC_YAML")
    fi
fi

# Count cameras
if [[ -z "$CAMERAS" ]]; then
    CAMERA_COUNT=0
else
    CAMERA_COUNT=$(echo "$CAMERAS" | wc -l)
fi

echo -e "${CYAN}Found $CAMERA_COUNT camera(s) with go2rtc_source configured${NC}"

# Write the static section (preserved as-is)
echo "$STATIC_PART" > "$GO2RTC_YAML"
echo "" >> "$GO2RTC_YAML"

# Write the auto-generated video relay section header
cat >> "$GO2RTC_YAML" << 'EOF'
  # =========================================================================
  # VIDEO RELAY STREAMS (auto-generated by scripts/update_go2rtc_config.sh)
  # =========================================================================
  # DO NOT EDIT BELOW THIS LINE — changes will be overwritten on restart
  #
  # Each camera with a go2rtc_source in cameras.json gets an entry here.
  # go2rtc connects to the camera (single consumer per camera) and re-exports:
  #   - WebRTC → browser (low-latency, DTLS-SRTP for iOS)
  #   - RTSP :8555/{serial} → FFmpeg for recording + motion detection
  #   - HLS :1984/api/... → iOS fallback if WebRTC fails
  #
  # Credential placeholders (${ENV_VAR}) are resolved by go2rtc at runtime
  # from environment variables injected by docker-compose.
  #
  # Source URL formats:
  #   Neolink/Baichuan:  rtsp://neolink:8554/{serial}/mainStream
  #   Reolink RTSP:      rtsp://${NVR_REOLINK_API_USER}:${NVR_REOLINK_API_PASSWORD}@{host}/h264Preview_01_main
  #   Eufy P2P:          eufy://${NVR_EUFY_BRIDGE_USERNAME}:${NVR_EUFY_BRIDGE_PASSWORD}@{serial}
  #   Amcrest:           rtsp://${NVR_AMCREST_LOBBY_USERNAME}:${NVR_AMCREST_LOBBY_PASSWORD}@{host}/...
  #   SV3C:              rtsp://admin:${NVR_SV3C_PASSWORD}@{host}:554/stream1
EOF

# Add each camera as a video relay stream
if [[ -n "$CAMERAS" ]]; then
    echo "$CAMERAS" | while read -r camera_json; do
        serial=$(echo "$camera_json" | jq -r '.serial')
        name=$(echo "$camera_json" | jq -r '.name')
        source=$(echo "$camera_json" | jq -r '.source')

        printf "\n  # %s (%s)\n" "$name" "$serial" >> "$GO2RTC_YAML"
        printf "  %s:\n" "$serial" >> "$GO2RTC_YAML"
        printf '    - "%s"\n' "$source" >> "$GO2RTC_YAML"

        echo -e " ${GREEN}+${NC} $name ($serial)"
    done
fi

echo -e "${GREEN}Done! go2rtc.yaml updated with $CAMERA_COUNT video relay stream(s)${NC}"
